//==========================================
// KonFIGURATION FILE
// 747-SIM.INC
//==========================================

//==========================================
// QProc definitions MCP (data from FS to EPIC )
//===========================================
defineqproc(142,AP1Off)
defineqproc(143,AP1On)
defineqproc(144,AP2Off)
defineqproc(145,AP2On)
defineqproc(146,AP3Off)
defineqproc(147,AP3On)
defineqproc(50,VSOff)
defineqproc(51,VSOn)
defineqproc(20,ALTOff)
defineqproc(21,ALTOn)
defineqproc(40,APPOff)
defineqproc(41,APPOn)
defineqproc(128,LOCOff)
defineqproc(129,LOCOn)
defineqproc(132,LNAVOff)
defineqproc(133,LNAVOn)
defineqproc(22,HDGOff)
defineqproc(23,HDGOn)
defineqproc(136,FLCHOff)
defineqproc(137,FLCHOn)
defineqproc(46,SPDOff)
defineqproc(47,SPDOn)
defineqproc(138,THROff)
defineqproc(139,THROn)
// defineqproc(164,ATOff)
// defineqproc(165,ATOn)
// defineqproc(166,FDOff)
// defineqproc(167,FDOn)
defineqproc(134,VNAVOff)
defineqproc(135,VNAVOn)
// defineqproc(172,MACHOff)
// defineqproc(173,MACHOn)

