//----------------
//  VDXCODES.INC  for controlling enque16 commands
//----------------

//=============================================
// MCP
//=============================================
#define v_MCP_LOC		20
#define v_MCP_APP		21
#define v_MCP_SPD_MACH	28
#define v_MCP_VNAV	18
#define v_MCP_FO_FD	13
#define v_MCP_CP_FD	13
#define v_MCP_FO_FD_off	14
#define v_MCP_LNAV	19
#define v_MCP_FLCH	17
#define v_MCP_HDG		24
#define v_MCP_VS		23
#define v_MCP_ALT		22
#define v_MCP_AP1		25
#define v_MCP_AP2		26
#define v_MCP_AP3		27
#define v_MCP_AP_dis	29

#define c_MCP_ias		35
#define c_MCP_mach	36
#define c_MCP_vs		37
#define c_MCP_alt		38
#define c_MCP_hdg		39

//=============================================
// Captains EFIS
//=============================================
#define v_EFIS_METRIC	40
#define v_EFIS_VOR_1	41
#define v_EFIS_ADF_1	42
#define v_EFIS_ADF_2	43
#define v_EFIS_VOR_2	44
#define v_EFIS_WPT	45
#define v_EFIS_WXR	46	// VOR on Airbus	
#define v_EFIS_DATA	47
#define v_EFIS_STA	48	// NDB on Airbus 
#define v_EFIS_ARPT	49
#define v_EFIS_R10	50
#define v_EFIS_R20	51
#define v_EFIS_R40	52
#define v_EFIS_R80	53
#define v_EFIS_R160	54
#define v_EFIS_R320	55
#define v_EFIS_VORADF1	56	// Vor and ADF switch1 CP side is off
#define v_EFIS_VORADF2	57	// Vor and ADF switch2 CP side is off
#define v_EFIS_POS	33
#define v_EFIS_MAP	30
#define v_EFIS_VOR	32
#define v_EFIS_PLN	34
#define v_EFIS_APP	31
#define v_EFIS_DSPMODES	58	
#define v_EFIS_R640	59

//=============================================
// EDSP
//=============================================
#define v_EDSP_RCL	60	
#define v_EDSP_CANC	61
#define v_EDSP_GEAR	62
#define v_EDSP_DRS	63
#define v_EDSP_HYD	65
#define v_EDSP_ECS	66
#define v_EDSP_FUEL	68
#define v_EDSP_ELEC	69
#define v_EDSP_STAT	70
#define v_EDSP_ENG	72
